Fix deprecation message for str_starts_with
getsentry/sentry-laravel pull request #780
Opened 2023-09-27 14:32 UTC by simbig

str_starts_with(): passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/vendor/laravel/framework/src/illuminate/support/str.php on line 1298

2023-09-28 08:14 UTC, stayallive requested changes
Thanks for making the PR, have 1 little suggestion!

2023-09-28 08:14 UTC, stayallive commented on src/Sentry/Laravel/Tracing/Integrations/LighthouseIntegration.php
> +        if (!Str::startsWith($event->getTransaction() ?? '', 'lighthouse?')) {
How about we rewrite this as:

```suggestion
        if ($event->getTransaction() === null || !Str::startsWith($event->getTransaction(), 'lighthouse?')) {
```

That reads better to me and possibly saves some string operations that are not needed anyway.

2023-10-04 09:02 UTC, cleptric approved these changes

2023-10-04 09:02 UTC, merged

2023-10-04 11:02 UTC, cleptric commented
This was just released in [v3.8.1](https://github.com/getsentry/sentry-laravel/releases/tag/3.8.1)