Allow embedding SQL query bindings (parameters) in SQL query breadcrumbs and spans
getsentry/sentry-laravel pull request #932
Opened 2024-07-24 12:55 UTC by spawnia

I added a similar feature to Laravel in https://github.com/laravel/framework/pull/52192.

2024-07-24 12:59 UTC, spawnia commented on CHANGELOG.md
> +  To enable this feature, update your `config/sentry.php` file or set the `SENTRY_TRACE_SQL_BINDINGS_ENABLED` and `SENTRY_BREADCRUMBS_SQL_BINDINGS_ENABLED` environment variables to `embed`.
I considered the addition of an additional boolean configuration option for this, but found that this complicated the code and made it unclear which option had precedence over the existing options. However, I could see reverting back to making the options just a boolean and simply adopting the new behaviour?

2024-07-24 12:59 UTC, spawnia commented on config/sentry.php
> +        // Capture bindings in SQL query breadcrumbs. `true` or `append` shows them separate, `embed` inlines them
I shortened the prior part of the description to fit everything on a single short line still.

2024-07-24 13:37 UTC, cleptric requested changes
This breaks our [Querries Insights Module](https://docs.sentry.io/product/insights/queries/), as it only works with parameterized queries.

We could debate adding the raw query to span data, but I currently don't see it that useful given the amount of changes required.

2024-07-24 14:05 UTC, spawnia commented
I think it would be massively useful to aid readability. I personally find it hard to decipher what is going on in the following example:

![image](https://github.com/user-attachments/assets/1061e559-d55a-4f31-ae49-15dce6584c7e)

The inlined version is much more readable to me.

```sql
update `mll_app_exa_type_hdr_link` set `expt_valid_to` = 20240724140225, `expt_change_user` = 'bfranke' where `expt_id` = '62A2C0AB-D321-4C6F-9675-4EF2AC77BD34' and `expt_valid_to` = 99991231235555
```

Queries Insights works with spans right? I would be more interested in breadcrumbs anways, maybe we could just make the change there and omit the extra option for spans?

2024-07-24 14:21 UTC, cleptric commented
This is something we can fix in the product, we do not need to add more logic to the SDK. The data is already there. cc @gggritso

2024-07-24 14:21 UTC, closed without merging

2024-07-24 14:55 UTC, spawnia commented
There are individual differences depending on the database or its configuration in how bindings are embedded, which is why the code that builds the raw SQL involves the `Connection` and `Grammar` classes. So I do not think that Sentry will be able to correctly build the SQL string from the data that is given in breadcrumbs. Would you consider a pull request that just offers the embedding for breadcrumbs? It should require fewer changes and provide the most value without breaking anything.

2024-07-24 15:17 UTC, cleptric commented
There are also concerns with server-side Pii stripping. Scrubbing individual data attributes is much easier than scrubbing a string, and I'm not sure we currently scrub breadcrumb descriptions. So a lot of reasons why I don't feel too happy about this change.

2024-07-24 15:31 UTC, spawnia commented
Are bindings such as the ones in the screenshot in https://github.com/getsentry/sentry-laravel/pull/932#issuecomment-2248061390 scrubbed? Seems difficult, given it is in the form of a list without keys that could indicate sensitive data.

2024-07-25 18:57 UTC, spawnia commented
Understood. Thanks for providing detailed feedback and discussing this pull request with me. I might try formulating a feature request over at https://github.com/getsentry/sentry.

2024-07-25 19:01 UTC, cleptric commented
We already looking into this, will hack something together next week. It’s a bit more involved but we want to have this feature 🙂