Compatibility with non default redis manager
getsentry/sentry-laravel pull request #957
Opened 2024-12-05 11:01 UTC by Kriso1337

change for compatibility with external redis manager (e.g. sentinel library in my case)

2024-12-05 11:18 UTC, stayallive requested changes
Is you sentinel `RedisManager` implementation open-source or from a package?

2024-12-05 11:18 UTC, stayallive commented on src/Sentry/Laravel/Features/CacheIntegration.php
>                  $redis->enableEvents();
The Factory does not contains `enableEvents` so we can't make this change as is: https://github.com/laravel/framework/blob/7db7ea950d3df663391718730f4490a4e189234a/src/Illuminate/Contracts/Redis/Factory.php.

2024-12-05 12:37 UTC, Kriso1337 commented
> Is you sentinel `RedisManager` implementation open-source or from a package?

from [package](https://packagist.org/packages/myqaa/laravel-redis-sentinel-drivers), it sounds like we can implement new interface here or maybe omit RedisManager type(and then add it to phpdoc)?

2024-12-05 12:58 UTC, stayallive commented
Thanks for linking the package, looks like this will work for that specific package.

> it sounds like we can omit RedisManager type(and then add it to phpdoc)?

I don't understand what you mean with this? Can you elaborate?

2024-12-05 13:04 UTC, Kriso1337 commented
> Thanks for linking the package, looks like this will work for that specific package.
> 
> > it sounds like we can omit RedisManager type(and then add it to phpdoc)?
> 
> I don't understand what you mean with this? Can you elaborate?

sure, here it is, with this realization it pass any RedisManager, default and any with implemented contract, so we can use custom manager

or maybe I didn't understand you and you are worried about another problem?

2024-12-08 11:18 UTC, stayallive commented
So the main concern is that Sentry is installed in many applications and if we ask to container to give us an object of the `Illuminate\Contracts\Redis\Factory` type it can be any object. Not only the default Laravel one or the one from the Sentinel package. So it isn't guaranteed that `enableEvents` is there to call. In fact the contract guarantees it is not, but it might be.

Since there is no real good workaround this we are not making this change at this time. You can add the following snippet to your own `AppServiceProvider` which has the same effect and the Sentry SDK will be able to use the events to show the Redis operations as if it enabled the events itself:

```php
$this->app->afterResolving(\Monospice\LaravelRedisSentinel\RedisSentinelManager::class, static function (\Monospice\LaravelRedisSentinel\RedisSentinelManager $redis): void {
    $redis->enableEvents();
});
```

2024-12-08 11:18 UTC, closed without merging